/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/youbot/Simulation_Examples/towerOfHanoi_ROS/catkin_ws/src/vrep_common/srv/simRosEnableSubscriber.srv
 *
 */


#ifndef VREP_COMMON_MESSAGE_SIMROSENABLESUBSCRIBERREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSENABLESUBSCRIBERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosEnableSubscriberRequest_
{
  typedef simRosEnableSubscriberRequest_<ContainerAllocator> Type;

  simRosEnableSubscriberRequest_()
    : topicName()
    , queueSize(0)
    , streamCmd(0)
    , auxInt1(0)
    , auxInt2(0)
    , auxString()  {
    }
  simRosEnableSubscriberRequest_(const ContainerAllocator& _alloc)
    : topicName(_alloc)
    , queueSize(0)
    , streamCmd(0)
    , auxInt1(0)
    , auxInt2(0)
    , auxString(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topicName_type;
  _topicName_type topicName;

   typedef int32_t _queueSize_type;
  _queueSize_type queueSize;

   typedef int32_t _streamCmd_type;
  _streamCmd_type streamCmd;

   typedef int32_t _auxInt1_type;
  _auxInt1_type auxInt1;

   typedef int32_t _auxInt2_type;
  _auxInt2_type auxInt2;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _auxString_type;
  _auxString_type auxString;




  typedef boost::shared_ptr< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct simRosEnableSubscriberRequest_

typedef ::vrep_common::simRosEnableSubscriberRequest_<std::allocator<void> > simRosEnableSubscriberRequest;

typedef boost::shared_ptr< ::vrep_common::simRosEnableSubscriberRequest > simRosEnableSubscriberRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosEnableSubscriberRequest const> simRosEnableSubscriberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vrep_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'vrep_common': ['/home/youbot/Simulation_Examples/towerOfHanoi_ROS/catkin_ws/src/vrep_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7df7c248dc5801f9f5b98f61f3741b8";
  }

  static const char* value(const ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7df7c248dc5801fULL;
  static const uint64_t static_value2 = 0x9f5b98f61f3741b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosEnableSubscriberRequest";
  }

  static const char* value(const ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
string topicName\n\
int32 queueSize\n\
int32 streamCmd\n\
int32 auxInt1\n\
int32 auxInt2\n\
string auxString\n\
";
  }

  static const char* value(const ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topicName);
      stream.next(m.queueSize);
      stream.next(m.streamCmd);
      stream.next(m.auxInt1);
      stream.next(m.auxInt2);
      stream.next(m.auxString);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct simRosEnableSubscriberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosEnableSubscriberRequest_<ContainerAllocator>& v)
  {
    s << indent << "topicName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topicName);
    s << indent << "queueSize: ";
    Printer<int32_t>::stream(s, indent + "  ", v.queueSize);
    s << indent << "streamCmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.streamCmd);
    s << indent << "auxInt1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.auxInt1);
    s << indent << "auxInt2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.auxInt2);
    s << indent << "auxString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.auxString);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSENABLESUBSCRIBERREQUEST_H
